default: &default
  adapter: postgresql
  encoding: unicode
  username: ton_nom_utilisateur_mac  
  password:
  host: localhost

development:
  <<: *default
  database: mon_appli_development

test:
  <<: *default
  database: mon_appli_test

production:
  <<: *default
  database: mon_appli_production
  username: mon_appli
  password: <%= ENV['MON_APPLI_DATABASE_PASSWORD'] %>
